### ISSUE TITLE
Initial value for h->max should not be __DBL_MIN__

### ISSUE THREAD

**Issue by igorconom** [RedisBloom/t-digest-c#18]
https://github.com/RedisBloom/t-digest-c/blob/8d7c50e2c9a82fbf11829a7a7f1767545afa0aea/src/tdigest.c#L103

`h->max` should no be `__DBL_MIN__` .  The` __DBL_MIN__` is the smallest _positive_ double , not the smallest double.
Quick fix:
```
 h->min = __DBL_MAX__;
 h->max = -h->min;
```

**Comment by filipecosta90** [comment]
Hi there @igorconom , thank you for catching this one. Do you want to submit a PR for it?

**Comment by igorconom** [comment]
Will do. Kind of new at with github, so bare with me if I missed some policy or guideline (I do have some mileage with git though).
